### Numpy

## Equipe

* Johnny Cleiton
* Joss Timoteo
* Raphael Feitosa

1 - Utilize o método `numpy.info` para obter informações do método `numpy.add`.

In [1]:
# Insira a resposta abaixo.
# o método numpy.info se comporta como o help()
import numpy as np

np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

2 - Utilize a função *range* do python para criar automaticamente uma lista de números variando de 0 até 15.

In [6]:
# Insira a resposta abaixo.
lista = list(range(0, 16))
print (lista)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


3 - Converta a lista criada para um objeto do tipo numpy array.

In [7]:
# Insira a resposta abaixo.
array = np.array(lista)
print (array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


4 - Crie um  novo array equivalente ao anterior utilizando diretamente os recursos do numpy.

In [8]:
# Insira a resposta abaixo.
array = np.arange(0, 16)
print (array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


5 - A partir do último array utilizado anteriormente, realize os seguintes procedimentos:

1. Exiba o formato atual do array.
2. Altere o formato para (4, 4).
3. Exiba novamente o formato do array após redimensioná-lo.

In [9]:
# Insira a resposta abaixo.

# Passo 1
print ("Formato original:", array.shape)

# Passo 2
array = array.reshape(4, 4)

# Passo 3
print ("Novo formato:", array.shape)
print (array)

Formato original: (16,)
Novo formato: (4, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


6 - Compute a média, mediana e o desvio padrão do array resultante da questão anterior.

In [11]:
# Insira a resposta abaixo.
media = np.mean(array)
mediana = np.median(array)
desvio_padrao = np.std(array)

print ("Média:", media)
print ("Mediana:", mediana)
print ("Desvio padrão:", desvio_padrao)

Média: 7.5
Mediana: 7.5
Desvio padrão: 4.6097722286464435


7 - Crie uma cópia do array atual  e transforme todos os números em valores negativos.

In [13]:
# Insira a resposta abaixo.

# cria uma cópia do array
array_negativo = array.copy()

# transforma todos os valores em negativos
array_negativo = -array_negativo

print (array_negativo)

[[  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]
 [-12 -13 -14 -15]]


8 - Realize os seguintes procedimentos:

1. Concatene verticalmente (*row-wise*) o array de números positivos com o array de números negativos.

2. Concatene horizontalmente (*column-wise*) o array resultante do passo 1 com ele mesmo.

3. Concatene em profundidade três cópias do array resultante do passo anterior, exibindo o formato final.

Como fazer?

> Analise a documentação das funções `stack`, `hstack` e `dstack` da biblioteca numpy.

In [19]:
# Passo 1 - Concatenação vertical (row-wise)
array_positivo = array

array_vertical = np.vstack((array_positivo, array_negativo))
print ("Vertical (8x4):\n", array_vertical)

Vertical (8x4):
 [[  0   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]
 [  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]
 [-12 -13 -14 -15]]


In [20]:
# Passo 2 - Concatenação horizontal (column-wise)
array_horizontal = np.hstack((array_vertical, array_vertical))
print ("Horizontal (8x8):\n", array_horizontal)

Horizontal (8x8):
 [[  0   1   2   3   0   1   2   3]
 [  4   5   6   7   4   5   6   7]
 [  8   9  10  11   8   9  10  11]
 [ 12  13  14  15  12  13  14  15]
 [  0  -1  -2  -3   0  -1  -2  -3]
 [ -4  -5  -6  -7  -4  -5  -6  -7]
 [ -8  -9 -10 -11  -8  -9 -10 -11]
 [-12 -13 -14 -15 -12 -13 -14 -15]]


In [21]:
# Passo 3 - Concatenação em profundidade (depth-wise)
array_profundidade = np.dstack((array_horizontal, array_horizontal, array_horizontal))
print ("Profundidade (8x8x3):\n", array_profundidade)
print ("Formato final:", array_profundidade.shape)

Profundidade (8x8x3):
 [[[  0   0   0]
  [  1   1   1]
  [  2   2   2]
  [  3   3   3]
  [  0   0   0]
  [  1   1   1]
  [  2   2   2]
  [  3   3   3]]

 [[  4   4   4]
  [  5   5   5]
  [  6   6   6]
  [  7   7   7]
  [  4   4   4]
  [  5   5   5]
  [  6   6   6]
  [  7   7   7]]

 [[  8   8   8]
  [  9   9   9]
  [ 10  10  10]
  [ 11  11  11]
  [  8   8   8]
  [  9   9   9]
  [ 10  10  10]
  [ 11  11  11]]

 [[ 12  12  12]
  [ 13  13  13]
  [ 14  14  14]
  [ 15  15  15]
  [ 12  12  12]
  [ 13  13  13]
  [ 14  14  14]
  [ 15  15  15]]

 [[  0   0   0]
  [ -1  -1  -1]
  [ -2  -2  -2]
  [ -3  -3  -3]
  [  0   0   0]
  [ -1  -1  -1]
  [ -2  -2  -2]
  [ -3  -3  -3]]

 [[ -4  -4  -4]
  [ -5  -5  -5]
  [ -6  -6  -6]
  [ -7  -7  -7]
  [ -4  -4  -4]
  [ -5  -5  -5]
  [ -6  -6  -6]
  [ -7  -7  -7]]

 [[ -8  -8  -8]
  [ -9  -9  -9]
  [-10 -10 -10]
  [-11 -11 -11]
  [ -8  -8  -8]
  [ -9  -9  -9]
  [-10 -10 -10]
  [-11 -11 -11]]

 [[-12 -12 -12]
  [-13 -13 -13]
  [-14 -14 -14]
  [-15 -15 -15]
  [

9 - Utilize o array do passo 1 da questão anterior e transforme os valores da segunda e terceira colunas em 1.

In [23]:
# Insira a resposta abaixo.

# transformar a 2ª e 3ª colunas em 1
array_vertical[:, 1:3] = 1

print (array_vertical)

[[  0   1   1   3]
 [  4   1   1   7]
 [  8   1   1  11]
 [ 12   1   1  15]
 [  0   1   1  -3]
 [ -4   1   1  -7]
 [ -8   1   1 -11]
 [-12   1   1 -15]]


10 - Adicione 2.5 a todos os valores presentes no array resultante da etapa anterior.

In [25]:
# Insira a resposta abaixo.
array_soma = array_vertical + 2.5

print (array_soma)

[[  2.5   3.5   3.5   5.5]
 [  6.5   3.5   3.5   9.5]
 [ 10.5   3.5   3.5  13.5]
 [ 14.5   3.5   3.5  17.5]
 [  2.5   3.5   3.5  -0.5]
 [ -1.5   3.5   3.5  -4.5]
 [ -5.5   3.5   3.5  -8.5]
 [ -9.5   3.5   3.5 -12.5]]


11 - Realize as seguintes operações:
1. Crie uma matriz com valor 3 em todas as posições com dimensionalidade (4, 2).
2. Crie uma matriz identidade de dimensionalidade (4, 4).
3. Compute o produto entre a transposta da primeira matriz e a matriz identidade, apresentando o resultado final.

In [32]:
# Insira a resposta abaixo.

# Passo 1
matriz3 = np.full((4, 2), 3)
print ("Matriz 4x2 com valor 3:\n", matriz3)

Matriz 4x2 com valor 3:
 [[3 3]
 [3 3]
 [3 3]
 [3 3]]


In [33]:
# Passo 2
identidade = np.eye(4)
print ("Matriz identidade 4x4:\n", identidade)

Matriz identidade 4x4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [34]:
# Passo 3
resultado = matriz3.T @ identidade
print ("Produto da transposta com a identidade:\n", resultado)

Produto da transposta com a identidade:
 [[3. 3. 3. 3.]
 [3. 3. 3. 3.]]


12 - Realize as seguintes operações:
1. Crie uma nova matriz de valores inteiros de 25 até 49 com dimensionalidade (5,5).
2. Crie uma nova matriz com valores uniformemente espaçados entre 0 e 1 e defina a sua dimensionalidade em (5,1).
3. Concatene horizontalmente as duas matrizes criadas anteriormente.

In [35]:
# Insira a resposta abaixo.

# Passo 1
matriz_inteiros = np.arange(25, 50).reshape(5, 5)
print ("Matriz 5x5 de inteiros:\n", matriz_inteiros)

Matriz 5x5 de inteiros:
 [[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [38]:
# Passo 2
matriz_uniforme = np.linspace(0, 1, 5).reshape(5, 1)
print ("Matriz 5x1 de valores uniformes:\n", matriz_uniforme)

Matriz 5x1 de valores uniformes:
 [[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


In [39]:
# Passo 3
matriz_concatenada = np.hstack((matriz_inteiros, matriz_uniforme))
print ("Matriz concatenada 5x6:\n", matriz_concatenada)

Matriz concatenada 5x6:
 [[25.   26.   27.   28.   29.    0.  ]
 [30.   31.   32.   33.   34.    0.25]
 [35.   36.   37.   38.   39.    0.5 ]
 [40.   41.   42.   43.   44.    0.75]
 [45.   46.   47.   48.   49.    1.  ]]


13 - Crie uma nova matriz com dimensionalidade (5,1) com números uniformemente espaçados utilizando um espaço logarítmico ao invés de um espaço linear.

In [40]:
# Insira a resposta abaixo.
matriz_log = np.logspace(0, 1, 5).reshape(5, 1)

print("Matriz 5x1 com espaço logarítmico:\n", matriz_log)

Matriz 5x1 com espaço logarítmico:
 [[ 1.        ]
 [ 1.77827941]
 [ 3.16227766]
 [ 5.62341325]
 [10.        ]]


14 - Crie uma função que receba um array e adicione uma borda composta de zeros nos quatro lados do array. Utilize o array resultante da questão anterior para testar o método criado.

In [43]:
# Insira a resposta abaixo.
def adicionar_borda_zeros(array):
    return np.pad(array, pad_width=1, mode='constant', constant_values=0)

matriz_com_borda = adicionar_borda_zeros(matriz_log)
print ("Array com borda de zeros:\n", matriz_com_borda)

Array com borda de zeros:
 [[ 0.          0.          0.        ]
 [ 0.          1.          0.        ]
 [ 0.          1.77827941  0.        ]
 [ 0.          3.16227766  0.        ]
 [ 0.          5.62341325  0.        ]
 [ 0.         10.          0.        ]
 [ 0.          0.          0.        ]]


15 - Crie um array de 36 números aleatórios oriundos de uma distribuição normal. Exiba o valor máximo, mínimo, a média e o desvio padrão desse array.

In [45]:
# Insira a resposta abaixo.

# cria um array de 36 números aleatórios com distribuição normal padrão (média=0, desvio=1)
array_normal = np.random.randn(36)

print ("Máximo:", np.max(array_normal))
print ("Mínimo:", np.min(array_normal))
print ("Média:", np.mean(array_normal))
print ("Desvio padrão:", np.std(array_normal))

Máximo: 2.1617492589450347
Mínimo: -2.128716942516067
Média: 0.3004137195608041
Desvio padrão: 0.9210067721807428
